# Generated by Django 5.1.6 on 2025-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
