# Generated by Django 5.1.6 on 2025-02-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', '已申请'), ('interview_scheduled', '待面试'), ('interviewed', '已面试'), ('offer_sent', '面试通过'), ('rejected', '不通过')], default='submitted', max_length=20),
        ),
    ]
