# Generated by Django 5.1.6 on 2025-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_chatmessage_attachment_chatmessage_attachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('salary_range', models.CharField(max_length=100)),
                ('original_url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('new', '新爬取'), ('processed', '已处理'), ('failed', '处理失败'), ('ignored', '已忽略')], default='new', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='jobs_rawjob_status_14c86e_idx'), models.Index(fields=['source'], name='jobs_rawjob_source_57a2fb_idx'), models.Index(fields=['created_at'], name='jobs_rawjob_created_6c25e2_idx')],
            },
        ),
    ]
