# Generated by Django 5.1.6 on 2025-02-23 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rawjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='rawjob',
            name='jobs_rawjob_status_14c86e_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawjob',
            name='jobs_rawjob_source_57a2fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawjob',
            name='jobs_rawjob_created_6c25e2_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='rawjob',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='job',
            name='claim_status',
            field=models.CharField(choices=[('unclaimed', '未认领'), ('claimed', '已认领'), ('auto_claimed', '自动认领')], default='unclaimed', max_length=20),
        ),
        migrations.AddField(
            model_name='rawjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='status',
            field=models.CharField(choices=[('new', '新抓取'), ('processed', '已处理'), ('failed', '处理失败'), ('ignored', '已忽略')], default='new', max_length=20),
        ),
    ]
