# Generated by Django 5.1.6 on 2025-02-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawjob',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='rawjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rawjob',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawjob',
            name='original_url',
            field=models.URLField(max_length=255),
        ),
    ]
